### ISSUE TITLE
Single Tags Split

### ISSUE THREAD

**Issue by Jekplex** [prtksxna/zuari#79]
I found a small issue. 
Tags tend to get split up the longer they are.
Those highlighted in red are single tags.
[ Probably not a priority, just a little visual bug that I've noticed. ]

![image](https://user-images.githubusercontent.com/41015593/61205562-4b739400-a6e8-11e9-8fe7-0ffae9260df0.png)

**Comment by prtksxna** [comment]
Thanks for reporting this @Jekplex! I noticed this one too, will try to get it fixed in the next release.

**Comment by prtksxna** [comment]
Hey @Jekplex, version `1.2.1` of the theme should be available as an update soon. That should fix this issue for you.
