### ISSUE TITLE
Trying to iterate over empty post tags array causes warning

### ISSUE THREAD

**Issue by craig02445** [prtksxna/zuari#94]
I am getting this error when running a Child Theme Configurator:

Warning:  Invalid argument supplied for foreach() in /home/femalesinhistory/femalesinherstory.com/wp-content/themes/zuari/inc/template-tags.php on line 55

**Comment by prtksxna** [comment]
Thanks for reporting this @craig02445! I think the issue is that I am not checking if there are any tags to begin with as mentioned in https://codex.wordpress.org/Function_Reference/get_the_tags

I'll try to push out a fix soon.
